[test]
coverageSkipTestFiles = true
coverageReporter = ["text", "lcov"]
coverageDir = "coverage"
coverageThreshold = { lines = 1.0, functions = 1.0 }
coveragePathIgnorePatterns = [
  "src/components/ui/**",
  "src/composables/__testing.ts",
  "src/pages/**",
  "src/router/**",
  "src/App.vue",
  "src/main.ts",
]
